# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
require 'csv'


# add mountains from mountains csv
CSV.foreach("./db/data/mountains.csv", :headers => true) do |row|
  attributes = {
    name: row[0],
    latitude: row[1],
    longitude: row[2],
    height: row[3]
  }

  mountain = Mountain.where(attributes)

  if mountain.first.nil?
    Mountain.create(attributes)
  end

end

all_lists = [
        "White Mountain Four Thousand Footers",
        "New England Four Thousand Footers",
        "New England Hundred Highest",
        "Northeast 111",
        "Adirondack 46ers"
        ]

all_lists.each do |list_name|
  new_list = List.where(title: list_name)
  if new_list.first.nil?
    List.create(title: list_name)
  end
end

full_lists = {
  "White Mountain Four Thousand Footers" => [
    "Washington",
    "Adams",
    "Jefferson",
    "Monroe",
    "Madison",
    "Lafayette",
    "Lincoln",
    "South Twin",
    "Carter Dome",
    "Moosilauke",
    "Eisenhower",
    "North Twin",
    "Carrigain",
    "Bond",
    "Middle Carter",
    "West Bond",
    "Garfield",
    "Liberty",
    "South Carter",
    "Wildcat",
    "Hancock",
    "South Kinsman",
    "Field",
    "Osceola",
    "Flume",
    "South Hancock",
    "Pierce",
    "North Kinsman",
    "Willey",
    "Bondcliff",
    "Zealand",
    "North Tripyramid",
    "Cabot",
    "Osceola-East Peak",
    "Middle Tripyramid",
    "Cannon",
    "Hale",
    "Jackson",
    "Tom",
    "Wildcat D",
    "Moriah",
    "Passaconaway",
    "Owls Head",
    "Galehead",
    "Whiteface",
    "Waumbek",
    "Isolation",
    "Tecumseh"
    ],
  "New England Four Thousand Footers" => [
    "Washington",
    "Adams",
    "Jefferson",
    "Monroe",
    "Madison",
    "Katahdin-Baxter",
    "Lafayette",
    "Lincoln",
    "South Twin",
    "Carter Dome",
    "Moosilauke",
    "Eisenhower",
    "North Twin",
    "Katahdin-Hamlin",
    "Carrigain",
    "Bond",
    "Middle Carter",
    "West Bond",
    "Garfield",
    "Liberty",
    "South Carter",
    "Wildcat",
    "Hancock",
    "Mansfield",
    "South Kinsman",
    "Field",
    "Osceola",
    "Flume",
    "South Hancock",
    "Pierce",
    "North Kinsman",
    "Willey",
    "Bondcliff",
    "Zealand",
    "Sugarloaf",
    "Killington",
    "Crocker",
    "North Tripyramid",
    "Cabot",
    "Old Speck",
    "Osceola-East",
    "North Brother",
    "Bigelow-West Peak",
    "Middle Tripyramid",
    "Saddleback",
    "Cannon",
    "Bigelow-Avery Peak",
    "Camels Hump",
    "Ellen",
    "Hale",
    "Jackson",
    "Tom",
    "Abraham-Maine",
    "South Crocker",
    "Wildcat D",
    "Moriah",
    "Passaconaway",
    "Owls Head",
    "Galehead",
    "Saddleback Mountain Horn",
    "Whiteface",
    "Redington",
    "Spaulding",
    "Abraham-Vermont",
    "Waumbek",
    "Isolation",
    "Tecumseh"
  ],
  "Adirondack 46ers" => [
    "Marcy",
    "Algonquin",
    "Haystack",
    "Skylight",
    "Whiteface",
    "Dix",
    "Gray",
    "Iroquois",
    "Basin",
    "Gothics",
    "Colden",
    "Giant",
    "Nippletop",
    "Santanoni",
    "Redfield",
    "Wright Peak",
    "Saddleback",
    "Panther",
    "TableTop",
    "Rocky Peak",
    "Macomb",
    "Armstrong",
    "Hough",
    "Seward",
    "Marshall",
    "Allen",
    "Big Slide",
    "Esther",
    "Upper Wolf Jaw",
    "Lower Wolf Jaw",
    "Street",
    "Phelps",
    "Donaldson",
    "Seymour",
    "Sawteeth",
    "Cascade",
    "South Dix",
    "Porter",
    "Colvin",
    "Emmons",
    "Dial",
    "East Dix",
    "Blake Peak",
    "Cliff",
    "Nye",
    "Couchsachraga"
    ],
  "New England Hundred Highest" => [
    "Sandwich",
    "South Brother",
    "Snow Mountain-Maine Franklin",
    "Pico",
    "The Bulge",
    "Stratton",
    "Nancy",
    "The Horn",
    "Weeks",
    "Weeks-South",
    "Goose Eye",
    "Vose Spur",
    "Fort",
    "Jay Peak",
    "White Cap",
    "Border Monuments",
    "Equinox",
    "Mendon Peak",
    "East Sleeper",
    "Bread Loaf",
    "Nubble Peak",
    "Bigelow South Horn",
    "Coe",
    "East Kennebago",
    "Wilson",
    "Big Jay",
    "Snow Mountain-Maine Oxford",
    "Baldpate",
    "Kennebago Divide",
    "Scar Ridge",
    "Elephant",
    "Dorset",
    "Cannon Balls",
    "Washington",
    "Adams",
    "Jefferson",
    "Monroe",
    "Madison",
    "Katahdin-Baxter",
    "Lafayette",
    "Lincoln",
    "South Twin",
    "Carter Dome",
    "Moosilauke",
    "Eisenhower",
    "North Twin",
    "Katahdin-Hamlin",
    "Carrigain",
    "Bond",
    "Middle Carter",
    "West Bond",
    "Garfield",
    "Liberty",
    "South Carter",
    "Wildcat",
    "Hancock",
    "Mansfield",
    "South Kinsman",
    "Field",
    "Osceola",
    "Flume",
    "South Hancock",
    "Pierce",
    "North Kinsman",
    "Willey",
    "Bondcliff",
    "Zealand",
    "Sugarloaf",
    "Killington",
    "Crocker",
    "North Tripyramid",
    "Cabot",
    "Old Speck",
    "Osceola-East",
    "North Brother",
    "Bigelow-West Peak",
    "Middle Tripyramid",
    "Saddleback",
    "Cannon",
    "Bigelow-Avery Peak",
    "Camels Hump",
    "Ellen",
    "Hale",
    "Jackson",
    "Tom",
    "Abraham-Maine",
    "South Crocker",
    "Wildcat D",
    "Moriah",
    "Passaconaway",
    "Owls Head",
    "Galehead",
    "Saddleback Mountain Horn",
    "The Horn",
    "Whiteface",
    "Redington",
    "Spaulding",
    "Abraham-Vermont",
    "Waumbek",
    "Isolation",
    "Tecumseh"
  ]
}

full_lists.each do |list_name, mountain_list|
  current_list = List.where(title: list_name).first
  mountain_list.each do |mountain_name|
    query = "%#{mountain_name}%"
    mountain = Mountain.where("name like ?", query).first
    if mountain.present?
      mountain_list_entry = MountainList.where(mountain_id: mountain.id, list_id: current_list.id).first
      if mountain_list_entry.nil?
        MountainList.create(mountain_id: mountain.id, list_id: current_list.id)
      end
    end
  end
end
